name: app
description: "ZenFlow - Personal Agenda Manager"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.6.0
  firebase_auth: ^6.3.0
  cloud_firestore: ^6.2.0
  google_sign_in: ^7.2.0
  googleapis: ^16.0.0
  http: ^1.4.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  intl: ^0.20.2
  shared_preferences: ^2.5.0
  get_it: ^8.0.3
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  firebase_auth_platform_interface: ^8.1.8
  firebase_core_platform_interface: ^6.0.3
  google_sign_in_platform_interface: ^3.1.0

flutter:
  uses-material-design: true
